# Generated by Django 6.1 on 2026-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_moneda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='logo1',
            new_name='FaviconEmpresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logo2',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='logo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logoEmpresa',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='faviconProyecto',
            field=models.ImageField(blank=True, null=True, upload_to='pro+yecto/logo/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logoProyecto',
            field=models.ImageField(blank=True, null=True, upload_to='pro+yecto/logo/'),
        ),
    ]
