# Generated by Django 6.1 on 2026-09-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_rename_logo1_empresa_faviconempresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='FaviconEmpresa',
            new_name='faviconEmpresa',
        ),
    ]
