# Generated by Django 6.1 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_rename_faviconempresa_empresa_faviconempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='faviconProyecto',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto/logo/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='logoProyecto',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto/logo/'),
        ),
    ]
