# Generated by Django 6.1 on 2026-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_faviconproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='brochureOficinas',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/brochure/'),
        ),
    ]
