# Generated by Django 6.1 on 2026-09-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [ migrations.RenameField(
        model_name="herostage",
        old_name="desktop",
        new_name="video",
    ),
]
