# Generated by Django 6.1 on 2026-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_rename_desktop_to_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostage',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto/hero/posters/'),
        ),
        migrations.AlterField(
            model_name='herostage',
            name='imagenHero',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto/hero/images/'),
        ),
        migrations.AlterField(
            model_name='herostage',
            name='video',
            field=models.FileField(upload_to='proyecto/hero/videos/'),
        ),
    ]
