# Generated by Django 6.1 on 2026-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_herostage_poster_alter_herostage_imagenhero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='imageUbicacionMobile',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto/ubicacion/'),
        ),
    ]
