# Generated by Django 6.1 on 2026-09-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_ubicacion_imageubicacionmobile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avance',
            name='avance_unico_por_mes',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='imagenosotros',
            name='nosotros',
        ),
        migrations.RemoveField(
            model_name='nosotros',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='ImageAvance',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='ImageNosotros',
        ),
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.DeleteModel(
            name='Avance',
        ),
    ]
