# Generated by Django 6.1 on 2026-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_remove_avance_avance_unico_por_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostage',
            name='videoURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
