function TitleCard ({
    image,
    label,
    title,
    highlight,
}) {
    return (
        <section
            className="
                relative
                mt-5
                h-[450px]
                w-full
                overflow-hidden
                rounded-2xl
                shadow-xl
                md:mt-10
        ">
            <img
                src={image}
                alt={title}
                className="
                    h-full
                    w-full
                    object-cover
                    transition-transform
                    duration-700
                    hover:scale-105
                "
            />
            <div
                className="
                    absolute
                    inset-0
                    bg-black/35
                "
            />
            <div
                className="
                    absolute
                    inset-x-0
                    top-0
                    p-6
                    md:p-10
            ">
                {label && (
                    <span
                        className="
                            text-xs
                            uppercase
                            tracking-[0.3em]
                            text-white
                    ">
                        {label}
                    </span>
                )}
                <h1
                    className="
                        mt-3
                        text-3xl
                        font-semibold
                        uppercase
                        leading-tight
                        text-white
                        md:text-5xl
                ">
                    {title}
                    {highlight && (
                        <span
                            className="
                                block
                                text-white/60
                            "
                        >
                            {highlight}
                        </span>
                    )}
                </h1>
            </div>
        </section>
    );
}
export default TitleCard;