# Generated by Django 6.1 on 2026-09-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0002_tipounidad_fichatecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='documentoVenta',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/ventas/'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='tipoVenta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pago total al contado'), (2, 'Anticipo / Reserva'), (3, 'Pagos parciales / Escalonados'), (4, 'Venta a plazos / Con reserva de propiedad'), (5, 'Crédito hipotecario (Bancario)')], null=True),
        ),
        migrations.AlterField(
            model_name='historialestadounidad',
            name='estado_anterior',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido')]),
        ),
        migrations.AlterField(
            model_name='historialestadounidad',
            name='estado_nuevo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido')]),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido')], default=1),
        ),
    ]
