# Generated by Django 6.1 on 2026-09-14 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0003_unidad_documentoventa_unidad_tipoventa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVentaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVenta', models.PositiveSmallIntegerField(choices=[(1, 'Pago total al contado'), (2, 'Anticipo / Reserva'), (3, 'Pagos parciales / Escalonados'), (4, 'Venta a plazos / Con reserva de propiedad'), (5, 'Crédito hipotecario (Bancario)')])),
                ('documentoVenta', models.FileField(upload_to='proyectos/historial_ventas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ventas', to='recorrido.unidad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
