# Generated by Django 6.1 on 2026-09-14 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0004_historialventaunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadounidad',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambio_estado', to='recorrido.historialventaunidad'),
        ),
    ]
