# Generated by Django 6.1 on 2026-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0005_historialestadounidad_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadounidad',
            name='estado_anterior',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido'), (3, 'Reservado')]),
        ),
        migrations.AlterField(
            model_name='historialestadounidad',
            name='estado_nuevo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido'), (3, 'Reservado')]),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido'), (3, 'Reservado')], default=1),
        ),
    ]
