# Generated by Django 6.1 on 2026-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0006_alter_historialestadounidad_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialventaunidad',
            name='tipoVenta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pago total al contado'), (2, 'Anticipo / Reserva'), (3, 'Pagos parciales / Escalonados'), (4, 'Venta a plazos / Con reserva de propiedad'), (5, 'Crédito hipotecario (Bancario)')], null=True),
        ),
    ]
