# Generated by Django 6.1 on 2026-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0007_alter_historialventaunidad_tipoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='moneda',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$US'), (2, 'BOB')], null=True),
        ),
    ]
