# Generated by Django 6.1 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0008_alter_unidad_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipounidad',
            name='fichaTecnica',
        ),
        migrations.AlterField(
            model_name='historialventaunidad',
            name='documentoVenta',
            field=models.FileField(upload_to='proyecto/historial_ventas/'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='documentoVenta',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/ventas/'),
        ),
    ]
